### ISSUE TITLE
Correct inconsistent naming used in Buildings.Controls.OBC package

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/modelica-buildings#1115]
There are naming inconsistencies, like in model `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.SetPoints.VAVSupplyTemperature`, `uOpeMod` was used in code, but using `opeMod` in html text.

**Comment by mwetter** [comment]
I created the branch `issue1115_obcDocumentation` to correct some documentation issues in the `OBC` package.

**Comment by milicag** [comment]
@JayHuLBL Thanks for identifying issues. I'm answering your email here for the sake of simpler tracking. I'm emailing corrected code and graphics, if you'd prefer to just copy entire blocks over having already created an issue. I can also push up to your branch if that's your preference.

* In model `G36_PR1.AHUs.MultiZone.Economizers.Subsequences.Limits`, should the html text “The fraction of the controller output signal between yMin and retDamConSigMin is linearly mapped” be “... between conSigMin and conSigFraOutDam...” (if according to the text in figure below), or should it be “... between yMin and uRetDamMin ...” (if according to the code)?

Correct, there is an error. The most convenient way to resolve it seems to be to take the notation used on the graphical representation, ```conSigFraOutDam```, to replace the following: in the html - ```retDamConSigMin```, in the code - ```uRetDamMin```. In addition, in the code I would replace ```sigFraForOutDam``` with ```conSigFra```.

* In model `G36_PR1.AHUs.MultiZone.Economizers.Subsequences.Enable`, it seems that there is no sequence for disable economizer according to zone state. But the html text says it has. Also, the threshold freeze protection stage is stage 0, while the threshold is stage 1 in `MultiZone.Economizers.Subsequences.Limits`.

The first part is correct, we've eliminated the zone state input, since it only applies to the single zone sequence. I've sent over the corrected image. The freeze protection stage, however, is a correct one - any stage above 0 will disable economizer and any stage above 1 will shut it down fully (including the minimal outdoor air).

Let me know if there are any further issues or if the tests with suggested edits show deviations from reference results.
