### ISSUE TITLE
error message for CDL.Continuous.LimPID in OMEdit

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1147]
Opening `MultiZone.VAV.Validation.Controller` in OMEdit shows the following error in the message browser:
```
[1] 09:55:36 Translation Error
[Buildings.Controls.OBC.CDL.Continuous.LimPID: 403:12-462:29]: Type mismatch for named argument in Line(points={{-80, -80}, {-80, -20}, {30, 60}, {80, 60}}). The argument has type:
  Integer[4, 2]
expected type:
  Real[2, :]
```
@JayHuLBL : can you please see if this can be corrected.

**Comment by JayHuLBL** [comment]
@mwetter I will look into it.

**Comment by JayHuLBL** [comment]
@mwetter It turns out that in OMEdit, it does not like to have more than two points in one line (in icon layer). Case like `Line(points={{-80, -80}, {-80, -20}, {30, 60}, {80, 60}})` which creates a linked lines will cause the error.
I changed it to 
```
Line(points={{-80,-80},{-80,-22}}, color={0,0,0}),
Line(points={{-80,-22},{6,56}}, color={0,0,0}),
Line(points={{6,56},{68,56}}, color={0,0,0})}),
```
It becomes correct for OMEdit. 
It seems to be fine to have multiple points in one line in Diagram layer in OMEdit, as it didn't give error message so far.

**Comment by mwetter** [comment]
Thanks, please make a pull request with the changes.
