### ISSUE TITLE
Test BuildingsPy, issue245_funnelIntegration

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1458]
This branch is to test the changes in BuildingsPy, branch issue245_funnelIntegration.

**Comment by AntoineGautier** [comment]
@mwetter The `'Time t is not strictly increasing.'` error comes from the function `Plotter.interpolate` in `io.postprocess`.
Could you please have a look at this function because I do not understand how the algorithm used to compute `tNew` (which uses `tInc = 10.0 * tTol`) is consistent with the condition checked for raising the exception (which uses `0.9 * tTol`)?

Looking into it made me realize that I kept unchanged the function `_getSimulationResults` from class `Tester` (the one that calls `Plotter.interpolate`) for consistency with the legacy comparison algorithm (and simplicity) but it actually limits to `self._nPoi = 101` the number of points being compared. However the good point is that it limits the size of the comparison files that are now stored on disk...

**Comment by mwetter** [comment]
The warning `Time t is not strictly increasing` has been fixed on the development branch.

**Comment by AntoineGautier** [comment]
@mwetter I just updated `runUnitTests.py` for Python 3 compatibility and `.gitignore` for additional output files from the new version of `buildingspy`.
Nothing else to commit on my side. So I believe before merging this branch into master we should:

- [ ] Merge `issue245_funnelIntegration` in `BuildingsPy/master`
- [ ] Reset `pip install git+https://github.com/lbl-srg/BuildingsPy@issue245_funnelIntegration` in `.travis.yml` to target the master branch again.
