### ISSUE TITLE
spawn hangs if simulated past the RunPeriod in the idf file

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1678]
Simulating `OneZoneOneOutputVariable` with  
```
experiment(
      StopTime=1032000,
      ...
```
causes spawn to hang at 7 days, which is the end of the EnergyPlus run period in the idf file. However, EnergyPlus should ignore the RunPeriod and stop if when `fmi2Terminate` is called, see https://lbl-srg.github.io/soep/softwareArchitecture.html#time-synchronization

**Comment by mwetter** [comment]
The development branch `issue1678_spawnIDFRunPeriodNotIgnored` reproduces the behavior for `Buildings/Experimental/EnergyPlus/Validation/OneZoneOneOutputVariable.mo`

@kbenne : Please address this in the next build. Easiest is to verify with OpenModelica and look at the log file to see where it is stuck because JModelica and Dymola seems to buffer writing of the log file and you won't see the last output. Can you also avoid that EnergyPlus terminates, except when `fmi2Terminate` is called, because otherwise the simulation freezes and log files are not guaranteed to show when the last exchange happened which makes it very hard to debug.

**Comment by kbenne** [comment]
@mwetter I figured out how to reference issues across repositories. I'm hoping you are getting notifications about these changes I am making.

**Comment by mwetter** [comment]
@kbenne I did not see notifications, other than what you wrote on this repo. Also, if you write things like "This should be fully addressed with NREL/Spawn@26fd4ac" is there a way to get notified when it is ready in a built for download? (Even if by manual email.)

**Comment by kbenne** [comment]
I thought maybe my commit message would give you a notification as it did show up here since I tagged it with this issue number.

I'm using `ref lbl-srg/modelica-buildings#1234` in my commit messages now to link to you issue. I will and have used "close" instead of "ref" when I think the work is sufficient to close the issue. I don't think it would automatically close issues across repositories, but within a repository that syntax would automatically close the issue when the commit was merged into the main develop branch.

All of these commits are being built by CI now. I'll look into automatically linking the builds from the commit for you. I have been manually triggering the CI to post to the drop location under "latest" at intervals we agree on, and I will do that again soon as I'm wrapping up a huge batch of work. I will include a curated log message for you so you can see that commits and changes that you are interested in.
