### ISSUE TITLE
Stopped fan model

### ISSUE THREAD

**Issue by tamandri** [lbl-srg/modelica-buildings#1833]
Hello,

On the fan model, I enter a pressure flow characteristics associated to 2000 rpm. In the case my ventilation system is not powered, and the fan does not run ( ~0 rpm), how should I set up the model to take that into consideration? I tried to simulate with 1 rpm and it runs very very slowly when that event happens. It seems very difficult to simulate.
How that case could be considered?
Thank you.

**Comment by mwetter** [comment]
The fans and pumps from the Buildings library should run with zero control signal, see for example `Buildings.Examples.VAVReheat.Guideline36` (There are many other examples in the library where we completely switch off fans and pumps.) 
Did you check what equation system causes the problem? Also, do you really have an event caused by the fan, and if so, what condition triggers the event? The fans should not trigger events as far as I know.

Please consult the manual of the simulation software you are using to see how to isolate the problem, as this usually points to the solution. If there is an issue with the equation system, please let us know. If the problem is with the solver, please consult the support of the tool provider. In either case, one would need a test model, ideally a small one, that reproduces the issue.
