### ISSUE TITLE
OptimalStartCoolingNegativeStartTime fails to simulate in Optimica

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#1842]
The model `Validation.OptimalStartCoolingNegativeStartTime` fails to simulate in Optimica. 
A support request has been sent to Modelon.

**Comment by kuzha** [comment]
The error message from Optimica is:
`CVodeError: The output and initial times are too close to each other. At time -536400.000000`

Modelon's reply: 
`"the underlying cause is two time events that are too close to each other. We are currently looking into how to best deal with this."`

To reproduce this error, change the parameter `duration` in the block OptimalStartCalculation.truHol to `duration=tOptMax+12*3600`

**Comment by mwetter** [comment]
This has been corrected on the master.
