### ISSUE TITLE
Solar geometry calculations use lat parameter for latitude

### ISSUE THREAD

**Issue by rurubino1** [lbl-srg/modelica-buildings#1860]
Hi, I noticed all base classes in `Buildings.BoundaryConditions.SolarGeometry.BaseClasses` use the parameter `lat` in all equations that need the latitude, eg. `Buildings.BoundaryConditions.SolarGeometry.BaseClasses.ZenithAngle`
Instead, the same base classes use outputs of the weather data reader for other values, eg. `decAng` and `solHouAng`.
If I'm not mistaken, this does not seem right, since in this way they don't use the actual latitude from the weather data, but a fixed parameter (user input).
The result is that changing weather data file to a location with a different latitude the solar geometry calculations are wrong (kind of a mix of the actual location and a location with latitude = whatever is selected in the `lat`parameter - unless the user manually changed the `lat` parameter everywhere to be consistent with the weather file.
NB: having `lat` as a parameter also prevents to simulate a moving "building", eg. a container traveling across the ocean...
To illustrate the issue, see attached a proposed corrected base class `ZenithAngleNew` and a little test.
[ZenithAngleNew.zip](https://github.com/lbl-srg/modelica-buildings/files/4401850/ZenithAngleNew.zip)
![ZenithAngle](https://user-images.githubusercontent.com/57481847/77896640-e1e8e500-7278-11ea-8f40-944443ec2c4a.PNG)

**Comment by mwetter** [comment]
@rurubino1 The results should be correct if you use the same latitude as in the weather data file. You can get the latitude from the weather data file as a parameter using `Buildings.BoundaryConditions.WeatherData.BaseClasses.getLatitudeTMY3`.

Using the latitude from the weather data bus would also work but it would require a reconfiguration of many models to remove this parameter from `Buildings.ThermalZones.Detailed.MixedAir` (and it will be slightly more expensive unless a Modelica tool recognizes this input to have parameter variability). For ships or shipping containers you still won't be able to use `MixedAir` because the orientation of the surface is likely also changing during the route.

**Comment by rurubino1** [comment]
thank you @mwetter, makes sense.
