### ISSUE TITLE
There is no impact of "Tau" on temperature gradient of stratified tank

### ISSUE THREAD

**Issue by amirjodeiri** [lbl-srg/modelica-buildings#1988]
Hello, 
I am currently working on new release (7.0.0) and I don't see any changes on temperature distribution along the tank with change of "time constant for mixing". Please confirm if this report is correct.
Kind regards,

**Comment by JayHuLBL** [comment]
@amirjodeiri If you run model `Buildings.Fluid.Storage.Examples.Stratified`, for the tank model `tanSim`, simply change the `tau` value will not change the temperature distribution since the hot water is injected from the top of the tank thus there will be no buoyancy driven mix. You will see the temperature distribution difference (when changing `tau`) if injecting hot water from the bottom. See in class `Buildings.Fluid.Storage.BaseClasses.Buoyancy`: 
```
   ...
  parameter Modelica.SIunits.Time tau(min=0) "Time constant for mixing";
...
  parameter Real k(unit="W/K") = V*rho_default*cp_default/tau/nSeg
    "Proportionality constant, since we use dT instead of dH";
...
  for i in 1:nSeg-1 loop
    dT[i] = heatPort[i+1].T-heatPort[i].T;
    Q_flow[i] = k*noEvent(smooth(1, if dT[i]>0 then dT[i]^2 else 0));
  end for;
...
```
and also check following image in `Buildings.Fluid.Storage.UsersGuide`:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/23491921/83668997-b7bbe800-a585-11ea-99b1-5321c86d4962.png">

**Comment by amirjodeiri** [comment]
@JayHuLBL thank you very much for your reply. I develop a model based on Stratified model in which the cold water is injected to the bottom of the tank and hot water is drawn from top of the tank. Under this condition, change of "tau" does not change the temperature as well.

**Comment by JayHuLBL** [comment]
Check the `tau`. It is a constant of mixing driven by buoyancy. In your case, it is correct that it should not change the temperature distribution.

**Comment by amirjodeiri** [comment]
To be clear, in a tank with 30 segments with inflow of cold water in segment 25 (there are still 5 segment below with higher temperature than inflow temperature) and outflow of hot water from segment 2, shouldn't be buoyancy-driven flow? There was no problem using Buildings 6.0.0 with this regard.

**Comment by amirjodeiri** [comment]
Dear @JayHuLBL,  I double check my model and I found the inlet location was not specify correctly, so I admit it was my mistake and the buoyancy work perfectly. Sorry for reporting this as an issue. Shall I close it?
