### ISSUE TITLE
UrbanOpt_SimpleRoomODE model and the lumped thermal conductance G

### ISSUE THREAD

**Issue by Helarga** [lbl-srg/modelica-buildings#2236]
For the 
Buildings.Experimental.DHC.Loads.SimpleRoomODE ,
the lumped thermal conductance <code>G</code> is evaluated as a function of <code>QHea_flow_nominal</code> and nominal air temperature difference between <code>TOutHea_nominal</code> and <code>TIndHea_nominal</code> for all operating conditions i.e. heating and cooling.
This approach results in having an equal <code>G</code> in case of heating and cooling which will  overestimate (underestimate if 
              <code>QHea_flow_nominal</code> **>** <code>QCoo_flow_nominal</code>) the <code>TAir</code> in case of cooling applications as shown below from the results of Buildings.Experimental.DHC.Loads.Validation.SimpleRoomODE at **case-1 and case-2**
![image](https://user-images.githubusercontent.com/47648835/98713593-0c3d6d80-2345-11eb-8e54-78c4810619ec.png)

**case-1** the <code>rooOdeCoo.TAir //1</code>profile is evaluated using the heating parameters i.e in case of cooling application 
![image](https://user-images.githubusercontent.com/47648835/98714981-c7b2d180-2346-11eb-9ee1-8fedaaf01d48.png)

**case-2** the <code>rooOdeCoo.TAir //2</code> profile  is evaluated using the cooling parameters i.e in case of cooling application 
![image](https://user-images.githubusercontent.com/47648835/98714886-abaf3000-2346-11eb-81d6-95b6f1c968da.png)

**Comment by AntoineGautier** [comment]
There is a misunderstanding of the modeling principles described in the documentation of `Buildings.Experimental.DHC.Loads.SimpleRoomODE`. Simply replacing `QHea_flow_nominal` by `QCoo_flow_nominal` in the equation used to compute `G` is incorrect.

- The steady state assumption is highly debatable for the peak cooling load.
- The user would need to provide additional parameters, namely the nominal solar and internal heat gains.

Based on the first plot you provide, it seems that you conclude that the model overestimates the room air temperature by comparing the model to itself. I cannot understand the reasoning here.

If you want to reformulate the model so that it relies only on parameters related to the cooling design conditions, please provide an updated mathematical description so that we can understand how you want to move forward with this issue. Otherwise this can be closed in my opinion.

**Comment by Helarga** [comment]
-The <code> G</code> value is evaluated as a function of <code>QHea_flow_nominal</code> and nominal air temperature difference between TOutHea_nominal and TIndHea_nominal.

Then this <code> G</code> value has been used at cooling applications in 
- Buildings.Experimental.DHC.Loads.Validation.SimpleRoomODE
- Buildings.Experimental.DHC.Loads.Validation.BaseClasses.FanCoil2PipeCooling

which will overestimate <code> Tair</code> as mentioned before.

-The above plots are comparing between the original model <code>case1</code> and the modified model <code>case2 </code>.
you may find the modified model at this PR https://github.com/lbl-srg/modelica-buildings/pull/2238 , for any further explanation please contact me.

-Would you share the ref. that you have used to assume that steady state thermal conductance calculated as a function of  heating nominal conditions( nominal heat flow and temperature difference) should be implemented also for cooling conditions, 

I have developed steady state and quasi steady state models for glazed buildings and i didn't hear about your approach 

https://www.sciencedirect.com/science/article/pii/S0378778815301249
https://www.sciencedirect.com/science/article/pii/S0378778814007749

it will be useful to read about another approach.

**Comment by AntoineGautier** [comment]
The equation `G = abs(Q_flow_nominal) / abs(TOut_nominal - TInd_nominal)` is incorrect at cooling design conditions. Please revise your PR consequently.
In the version on the master, the assumption of `G` being constant for all operating conditions is definitely a rough assumption, no arguing about that. I am totally open to a model reformulation if you find a way to reduce that modeling uncertainty without having the user provide too may additional parameters that he probably will not have access to.

**Comment by Helarga** [comment]
let's try to agree on the following items:

- the nominal heat flow which is evaluated from any " time series file on modelica for eg." includes all forms of heat transfer, internal gains, solar gains. I mean that if the nominal cooling flow rate <code>**Q_Coo_flow_nominal**</code>  = -10kW it means that the summation of internal gains,  solar gains, conduction HT, convection HT, radiation HT = 10kW.

- the same for heating , the nominal heating flow rate  <code>**Q_Hea_flow_nominal**</code>= 5kW means that the summation of -1* internal gains,  -1*solar gains, conduction HT, convection HT, radiation HT = 5kW ( -1 because the internal and solar gains are subtracted from the  heating loads).

- accordingly <code>G</code> represents all forms of heat transfer i.e convection, radiation, conduction or gains i.e. solar radiation, internal gains"  because as per the used equation in heating mode, it is equal to 

<code>**Q_Hea_flow_nominal**</code> / <code>Tind_Nominal</code> - <code>Toud_nominal</code>
 
and the same concept should be applied  in cooling, no problem at all 

<code>**Q_Coo_flow_nominal**</code> / <code>Tind_Nominal</code> - <code>Toud_nominal</code>

-----------------------------------------------------------------------------------------------
I hear your concern about having incorrect <code>G</code> out of considering  nominal cooling flow rate, your concern is valid if we need to calculate the <code>QCoo_flow_nominal</code>, at this case we have to add the internal and solar gains.

But this is not our case, we have already the nominal cooling value and what we care about is to use the <code>G</code> values that correspond to nominal heating flow rate  and nominal cooling flow rate to avoid under/overestimate <code>TAir </code> value.

That is why it makes sense to me to have two values of steady state <code>G</code>. We don't have walls , wall areas , thickness, we don't evaluate convection or conduction HT. The only thing that we have is this lumped thermal conductance or we can name it lumped HT, internal and solar loads [W/K].

if you are still not convinced with this explanation please tell me to restore the original model at the PR, no problem at all.

**Comment by AntoineGautier** [comment]
I disagree. You cannot 

- lump solar and internal heat gains into any thermal conductance of some sort as these quantities do not scale with the temperature difference between the indoor and outdoor environments,
- nor consider the coefficient that would result from such manipulation to be constant.

I can see in #2238 that you did not modify the model equations, nor the documentation section, just some parameter names and their description strings. Again, if you want to reformulate the model so that it relies only on parameters related to the cooling design conditions, please provide an updated mathematical description (similar to the one in the info section of `Experimental.DHC.Loads.SimpleRoomODE`) so that we can understand how you want to move forward with this issue.

**Comment by Helarga** [comment]
I disagree with the above two technical points.

I raised a technical problem "that you agreed with" and I proposed a solution "which you disagreed with" and i think that we don't need your suggestion of "reformulate the model so that it relies on parameters related to the cooling design conditions." 

so I suggest that we close the issue and keep the model as it is with its technical problem.
