### ISSUE TITLE
Correct documentation of comparison with hysteresis blocks

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2246]
In `Buildings.Controls.OBC.CDL.Continuous.Greater` this part of the documentation
`If h > 0, then the output switches to true if u1 > u2, and it switches to false if u1 > u2-h.`
should be 
`If h > 0, then the output switches to true if u1 > u2, and it switches to false if u1 < u2-h.`
The same applies to the other comparison blocks.
Also I wonder if `If h > 0` should not be deleted as anyway the parameter cannot take negative values due to `parameter Real h(final min=0)=0`.

**Comment by mwetter** [comment]
That's indeed an error in the documentation, thanks for fixing it.

The "If h > 0" should not be removed, because if h=0, then "Block that outputs true if the Real input u1 is greater than the Real input u2, optionally within a hysteresis h." applies.

The equation after "If h > 0...." is only valid if "h > 0", because 
```If h > 0, then the output switches to true if u1 > u2, and it switches to false if u1 < u2-h.```
is not correct for h=0. Consider h=0 and u1 > u2, then the output is true. Now, consider u1=u2. Then, the block outputs false, but the comment would not address this case.

**Comment by AntoineGautier** [comment]
Thanks, I missed that. Do you think it might be clearer to write `If h ≠ 0` then? (Which boils down to the same condition in the end, but in my case I mistakenly associated `>` to "positive" in the sense of "not negative" whereas what matters here is "non zero").

**Comment by mwetter** [comment]
Yes, I think `If h ≠ 0`  would be clearest.

**Comment by mwetter** [comment]
@AntoineGautier : Can you please make a PR with the suggested rewording.
