### ISSUE TITLE
Improvements to Data Center Package Models

### ISSUE THREAD

**Issue by khinkelman** [lbl-srg/modelica-buildings#2446]
Hi @AntoineGautier,

When working on the district cooling models, I found some mistakes in the data center package and areas that could use some improvement. They are relatively minor fixes, which are:

1. Some of the parallel fluid loops are modeled as ideal mixing junctions (see NonIntegrated model below as an example). With the temperature sensors, this produces erroneous readings at times. I'd like to add mixing junctions without pressure drops to avoid these unintended errors. 
2. The pressure drops are accidentally duplicated in both `dpFixed_nominal` (valve) and in-line fixed pressure resistance pipes. This causes the pressure drop declaration to be 2x what the user intended. See WatersideEconomizer below as an example (note, `dp1_nominal` is also declared within the `heaExh` block). I'd like to set `dpFixed_nominal` to 0 to avoid this confusion. 

Could you please open a new branch for me to make these improvements? Please let me know if you have any questions. 
Thanks!

**Buildings.Applications.DataCenters.ChillerCooled.Equipment.NonIntegrated** 
![image](https://user-images.githubusercontent.com/44682485/114218454-a8849400-9926-11eb-93e8-0143ea988c81.png)

**Buildings.Applications.DataCenters.ChillerCooled.Equipment.WatersideEconomizer**
![image](https://user-images.githubusercontent.com/44682485/114218189-5479af80-9926-11eb-91ab-41812cf5a2e1.png)

**Comment by AntoineGautier** [comment]
@khinkelman It's ready for you here https://github.com/lbl-srg/modelica-buildings/tree/issue2446_fixDataCenters
Regarding the nominal pressure drop of the heat exchanger, the best practice is actually to assign it to `dpFixed_nominal` of the control valve so that it gets lumped with `dpValve_nominal` and avoids the algebraic loop created by the two flow resistances in series, see https://simulationresearch.lbl.gov/modelica/userGuide/performance.html#reducing-nonlinear-equations-of-serially-connected-flow-resistances

**Comment by khinkelman** [comment]
Thanks @AntoineGautier! I agree that is the better approach numerically and will proceed as such.
