### ISSUE TITLE
SingleFamilyHouse.Unconditioned becomes unstable

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2451]
This issue reproduces the case where `SingleFamilyHouse.Unconditioned` becomes unstable.

The branch is based on abc6bf6cb7 which is from branch `issue2358_spawn_surface` from April 7 and uses Spawn commit bb45e764161ae42d9c2a9a67bfeb9423d596ac45.

The models are on the new branch `issue2451_spawn_Unconditioned_unstable`

To reproduce, run
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.Unconditioned", stopTime=4000, method="Cvode", tolerance=1e-06, resultFile="Unconditioned");
```
An example plot is
![image](https://user-images.githubusercontent.com/1329080/114778060-3bf40580-9d29-11eb-80cd-7ca8dc236d42.png)

**Comment by kbenne** [comment]
I am able to reproduce this using the commit you referenced (@mwetter) https://github.com/NREL/Spawn/commit/bb45e764161ae42d9c2a9a67bfeb9423d596ac45. The issue does not seem to be sensitive to the version of the test model in MBL. Several versions of the MBL and the corresponding SingleFamilyHouse.Unconditioned model showed this error. In my test numerical instability quickly becomes unbounded. You can see this in my plot of zone air temperature. 

![zone air](https://user-images.githubusercontent.com/707488/114902886-dc0a6700-9ddb-11eb-9865-604ea9144cc3.png)


Upon investigation I have isolated the commit where the regression happened to this one, and specifically these lines of code that add calls to the surface heat balance manager https://github.com/NREL/Spawn/commit/92ebd46c4e1b8d768b18e525ec8b87a0b08d5dc0#diff-c7db08e12430ad5b8f49060fd0893d457aa2173e72b398938073770dd44e6f28R452

These lines of code were added so that the surface heat flow outputs are updated when new surface temperature inputs are given. We have been suspecting that these calls cause instability and I see evidence in my testing that fairly definitively supports that conclusion. Additionally unit tests have shown that the surface heat balance calls were not idempotent as originally implemented. https://github.com/NREL/Spawn/blob/aef9bc9630e22e360225e47e76abfb698813f255/test/test_mbl_idf.cpp#L207

Upon recognizing this problem I made a change to the EnergyPlus implementation of EnergyPlus::HeatBalanceSurfaceManager::CalcHeatBalanceInsideSurf that appears to fix the issue. In the original implementation instead of iterating window surfaces a single time during the solver routine, I allow the windows to iterate through the solver just as the opaque surfaces do. I empirically found significantly more stability with respect to surface temperature and heat flux between calls of CalcHeatBalanceInsideSurf after making this change. https://github.com/NREL/EnergyPlus/commit/e579c2aa8290c7962e0814e11ecd1d79e14f7da4 There is some question as to if this is a prudent change to EnergyPlus. It no doubt involves some performance regression, and also it does change the EnergyPlus results as observed by the EnergyPlus CI reporting "diffs" in the regression suite. It may be that the changed answers are "more correct" but I really have no evidence to support of deny that claim.

There are Spawn builds posted that a) avoid the calls to surface heat balance altogether https://gitlab.com/kylebenne/spawn/-/pipelines/285853538 and b) implement the experimental change to EnergyPlus https://gitlab.com/kylebenne/spawn/-/pipelines/285948136 and both seem to address the issue in my testing, however offline conversation makes me think @mwetter did not see the issue clear up. I believe that might be because @mwetter you are looking at the heat flow derivative as the measure of stability, and I am looking at a more simple criteria which is simply the zone air temperature. I believe the artifacts you are seeing in derivatives may be long standing, however the instability and ultimate termination of simulation is new and caused by the issue outlined here. 

Here is the result for zone air temperature after implementing either a) avoid heat balance calls, or b) using the slightly modified EnergyPlus. Both approaches seem to address the runaway instability but may or may not address the error in numerically differentiating the zone heat flow during low load conditions.

![zone fixed](https://user-images.githubusercontent.com/707488/114907775-0b6fa280-9de1-11eb-8401-82b31e8a0626.png)

**Comment by kbenne** [comment]
For more detail here I am zoomed in on the Q flow and Q last flow. They are right on top of each other so it looks like a single line. In other words it appears that the computed heat flow is relatively steady which I think corresponds well with the near linear decay of the startup transient.

![zone-detail](https://user-images.githubusercontent.com/707488/115081655-48fc2a80-9eca-11eb-94a8-18704cfeb32d.png)

**Comment by mwetter** [comment]
I will close this as derivatives of outputs with respect to the room temperature are no longer computed.
