### ISSUE TITLE
VDI6007 validation test cases failing in OpenModelica

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#2713]
**Describe the bug**
While checking the OMC test reports of [Buildings 7.0.x](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/Buildings_maint.7.0.x.html) and [Buildings 9.0.0 dev](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) I noticed that all the VDI6007 validation test cases fail with the same error message:
```
assert            | warning | The following assertion has been violated at time 5184000.000000
|                 | |       | assEqu.nFai == 0
assert            | error   | Inputs differ by more than threShold.    Check output 'satisfied' for when violation(s) happened.
```
**To Reproduce**
1. Open model 'Buildings.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase1' and simulate it

**Expected behavior**
I'm not sure if this error is generated because the results are wrong, or because other Modelica tools are more tolerant with assertions. Can you please check and report?

Thanks!

**Comment by mwetter** [comment]
It looks like this is caused by events that are supposed to be simultaneous, but may not be due to rounding errors. Disabling the assertion and simulating the model in OpenModelica yields:
![image](https://user-images.githubusercontent.com/1329080/140346685-46638e03-9892-4b82-8730-036e15ebb9cb.png)

Note that in the 2nd and 3rd test period, the variable `assEqu.diff` is about 5.6. Zooming in on the last test period shows:
![image](https://user-images.githubusercontent.com/1329080/140348929-d6a65556-ce19-47dd-9bcc-50a9d349ba1b.png)
and
![image](https://user-images.githubusercontent.com/1329080/140349675-2f9b2b8b-7789-4424-a10e-dbb13fa7d66b.png)
The upstream signal is sampled with `Modelica.Blocks.Math.Mean` with `f = 1/3600`, and this block implements
```modelica
  when sample(t0 + 1/f, 1/f) then
    y = if not yGreaterOrEqualZero then f*pre(x) else max(0.0, f*pre(x));
    reinit(x, 0);
  end when;
```
So this is likely a rounding error due to the calculation of `1/(1/3600)` and the model implementation needs to be made robust against this.

**Comment by casella** [comment]
All [VDI test in Buildings 7.0.x](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/Buildings_maint.7.0.x.html) and [IBPSA 3.0.0](https://libraries.openmodelica.org/branches/master/IBPSA_latest/IBPSA_latest.html) are now reported to run successfully in OMC.

#2718 is still not merged on master, so we still don't see that [here](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html).
