### ISSUE TITLE
New simulation models in Buildings contain references to partial classes

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#2714]
**Describe the bug**
While scanning the OpenModelica test report of the [development version of Buildings 9.0.0](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html), I found that there are 18 models failing in the front end, vs. only three currently failing with Buildings 7.0.x maintenance, probably going to be fixed in #2706. 

I saw several instances of the same error, see e.g. [Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5.Validation.ChillerBorefield](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.EnergyTransferStations.Combined.Generation5.Validation.ChillerBorefield.err):
```
[Buildings 9.0.0-master/Experimental/DHC/EnergyTransferStations/Combined/Generation5/Validation/BaseClasses/PartialChillerBorefield.mo:63:3-84:72:writable]
Error: component ets contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.
```

This kind of issue was already addressed in the past, see e.g. #2229, #2230. Unfortunately Dymola and OCT accept those models that are clearly invalid according to the Modelica Specification, [section 5.3.2](https://specification.modelica.org/maint/3.5/scoping-name-lookup-and-flattening.html#composite-name-lookup).

I would suggest to:
- Regularly check the OpenModelica Jenkins [report of the development version](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html), specifically looking at the front-end column. Most issues with the OMC front-end have been resolved by now, so there is a decent chance that any error showing up there is actually an issue with the Buildings library, not with OMC.
- Look for such partial class instantiation errors in the reports for [8.0.0](https://libraries.openmodelica.org/branches/master/Buildings_8.0.0/Buildings_8.0.0.html) and [9.0.0](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) and fix them appropriately.
- Open a ticket with Dassault Systèmes and with Modelon, asking them to at least issue a warning in such cases, since the model is clearly not compliant with the language specification and this may hamper (as it does) compatibility with other tools that follow it more strictly

**Comment by AntoineGautier** [comment]
This issue stems from the base classes within `Buildings.Experimental.DHC.Networks.BaseClasses` that rely on constructs as illustrated in the minimum example below.

```
model MinimumExample
  partial model PartialComponent
    replaceable package Medium=Modelica.Media.Interfaces.PartialMedium;
    replaceable model SubComponentModel = PartialSubComponent (
      redeclare final package Medium=Medium);
    SubComponentModel subCom;
  end PartialComponent;

  partial model PartialSubComponent
    replaceable package Medium=Modelica.Media.Interfaces.PartialMedium;
    parameter Medium.ThermodynamicState sta_default=
      Medium.setState_pTX(T=Medium.T_default, p=Medium.p_default, X=Medium.X_default);
  end PartialSubComponent;

  model SubComponent
    extends PartialSubComponent;
  end SubComponent;

  model Component
    extends PartialComponent(redeclare model SubComponentModel = SubComponent);
  end Component;

  package Medium = Buildings.Media.Water;
  Component com(redeclare package Medium=Medium);
end MinimumExample;
```

Basically, a partial short class definition `SubComponentModel` is used to instantiate a subcomponent `subCom`. 
At the top level, the partial short class is redeclared so that the model is considered valid by Dymola and Optimica, but not by OpenModelica. 
There is a similar example provided at https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#short-class-definitions

```
[Example:
replaceable model Load=TwoPin;
Load R; // Error unless Load is redeclared since TwoPin is a partial class.
]
```
So we are in the case where `SubComponentModel` is indeed redeclared when extending `PartialComponent` so in my opinion the model `Component` that is ultimately instantiated should be considered valid according to the flattening process described at https://specification.modelica.org/maint/3.5/scoping-name-lookup-and-flattening.html#steps-of-instantiation

> For local classes and components in the current class, instance nodes are created and inserted into the current instance. Modifiers (including class redeclarations) are merged and associated with the instance and the element is partially instantiated.
[The partially instantiated elements are used later for lookup during the generation of the flat equation system and are instantiated fully, if necessary, using the stored modification environment.]

I understand from above that the full instantiation uses the modification environment, which includes class redeclarations. So going back to the minimum example, when `subCom` gets fully instantiated, any redeclaration should be considered for the class name lookup.

**Comment by casella** [comment]
@AntoineGautier, thanks for the analysis! I just checked your MinimumExample in OMC and got
```
[2] 11:58:59 Translation Notification
[MinimumExample: 10:17-10:71]: From here:

[3] 11:58:59 Translation Error
[MinimumExample: 24:3-24:49]: component com contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.
```
Intuitively I agree that this model should be valid, since both the Medium and the SubComponent models are both redeclared, one way or the other.

@perost will look into this and report.

**Comment by casella** [comment]
See [OpenModelica issue #8092](https://github.com/OpenModelica/OpenModelica/issues/8092).

**Comment by Elsa5473** [comment]
Hi! 
I am using the model Buildings.DHC.ETS.Combined.Subsystems.Validation.HeatPumpDHWTank in the version Buildings-v.11.0.0, and still get this error: 

"Ccomponent heaPum contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium." I am not sure how to fix it, because when I change in the Openmodelica code I always get an error. 

Have you got any more updates regarding this error? 
Thank you!

//Elsa

**Comment by JayHuLBL** [comment]
@Elsa5473 Running the same class `Buildings.DHC.ETS.Combined.Subsystems.Validation.HeatPumpDHWTank` in the current master branch with `OpenModelica version 1.24.0~dev-30-gdbec042`, there is no error anymore.
