### ISSUE TITLE
Addition of district cooling model: ETS, Loads and Examples

### ISSUE THREAD

**Issue by ChengnanShi-Work** [lbl-srg/modelica-buildings#2912]
Hi Dr. Hu @JayHuLBL , when you have a chance, could you please create a new branch for this issue so that I could add the developments?

This issue is to add the district cooling models to `Buildings.Experimental.DHC` package, including the followings:

### Buildings.Experimental.DHC
![image](https://user-images.githubusercontent.com/82961137/157284821-97b81c8d-b823-49ed-850e-3ce243a309b5.png)
![image](https://user-images.githubusercontent.com/82961137/157286352-72633ef1-d0f9-45c2-b1e5-90f3c20a7d23.png)
![image](https://user-images.githubusercontent.com/82961137/157286734-ba0c71ee-38c9-4b0a-8f2c-116c4858be1c.png)

**Model Descriptions**
These models including three typical types of energy transfer station, one time series building loads, and an example model for the integral district cooling system. This work is part of the URBANopt project and will be extended for GMT(Geojson Modelica Translator) usage.

Our team still need to 2 weeks (targeted to March 21st) to complete the internal review, if you have any questions, please let me know. Thanks a lot!

**Comment by JayHuLBL** [comment]
@ChengnanShi-Work I just created branch `issue2912_districtCooling` for the issue.

**Comment by ChengnanShi-Work** [comment]
Many thanks!


> @ChengnanShi-Work I just created branch `issue2912_districtCooling` for the issue.

**Comment by mwetter** [comment]
@khinkelman (and @Chengnan Shi and @JingWang-CUB as you seem to have co-authored some of the underlying models).

I reopen this issue again as the system model `Buildings.Experimental.DHC.Plants.Cooling.ElectricChillerParallel` on branch `issue2912_districtCooling`, commit 2bd29227ebda0e1b369026efd8ca7e191ba38285 has oscillations that in one model causes very slow progress, and in the other model the simulation fails.

The model `Buildings.Experimental.DHC.Examples.Cooling.DirectUncontrolledETS` makes very slow progress.
If simulated with
```
simulateModel("Buildings.Experimental.DHC.Examples.Cooling.DirectUncontrolledETS", startTime=15724800, stopTime=15728800, method="Cvode", tolerance=1e-06, resultFile="DirectUncontrolledETS");
```
the output `pla.chiWatPumCon.conPID.I.y` shows fast oscillations with a period of about 120 seconds, see below:

![DirectUncontrolledETS](https://user-images.githubusercontent.com/1329080/203442185-335b0761-f882-44c4-b0f1-d948dc664f83.png)

Also, the controls intent seems to be to maintain a differential pressure, which is input to the PI controller. The PI controller then outputs a signal, which is input to a finite state machine that outputs 0, 1 or 2 for the number of pumps to operate. However, the quantity that affects this differential pressure is the pump mode, which is 0, 1 pump or 2 pumps. Hence, the PI controller can only oscillate as the pump on/off won't be able to track the set point of the PI controller and hence the integrator will increase or decrease until the state machine switches the pump off or on again. (As a side-note, the hysteresis block is not needed as its input is either 0 or 1.) The figure below shows the control loop:

![PXL_20221122_233453752](https://user-images.githubusercontent.com/1329080/203442848-d9857c90-0759-409b-a6d6-57fbd03d20a5.jpg)


In addition, the state machine takes as an input also the chiller mass flow rate, so it uses one discrete actuation variable (pump 0, 1, 2) to control two quantities. This can't work, and likely needs cascading control.

Can you please redesign and reimplement the control of this system model.

Note that the model `Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel` also fails to simulate, likely because of the same problem as above. Here the last message is
```
Expression pla.chiWatPumCon.pumStaCon.speSig > pla.chiWatPumCon.pumStaCon.minSpe became false ( (pla.chiWatPumCon.pumStaCon.speSig)-(pla.chiWatPumCon.pumStaCon.minSpe) = -5.09501e-05 )
Warning: Event epsilon of pla.chiWatPumCon.pumStaCon.speSig <= pla.chiWatPumCon.pumStaCon.minSpe increased to 1e-05.

Expression pla.chiWatPumCon.pumStaCon.speSig <= pla.chiWatPumCon.pumStaCon.minSpe became true ( (pla.chiWatPumCon.pumStaCon.speSig)-(pla.chiWatPumCon.pumStaCon.minSpe) = -5.09501e-05 )
  Variable pla.pumCHW.hys[1].y = 0 at time 60

ERROR: Finding consistent restart conditions failed at time:  60
```
which points to the same controller.

**Comment by khinkelman** [comment]
Thanks @mwetter. Just a quick note to let you know that this is on my radar. I'll try to get to it asap (sometime this month).

**Comment by khinkelman** [comment]
Hi @mwetter, I've made progress on this issue and wanted to send an update and ask for your input. 

**Problems addressed to date:**
- In `*.Plants.Cooling.ElectricChillerParallel`: The chilled water bypass control was incorrectly measuring the flow through the bypass leg. I corrected this to measure the mass flow through the chiller CHW side (the control design is to maintain the minimum flow rate through this leg).
- In `*.Plants.Cooling.Controls.ChilledWaterPumpSpeed`: I normalized the PI controller inputs by `dpSetPoi`. I also added a reset to reduce the control output to `y=0.5` when the staging switches from 1 to 2 pumps. (This avoids the large jump you mentioned above.)
-  In `*.Plants.Cooling.Examples.ElectricChillerParallel`: I enabled filters for the CHW pumps and valves, which corrected some of the control problems. I also corrected the pressure drop in the example loop such that it is more appropriate based on the `dp` setpoint. With these changes, the plant example model now simulates quickly and as expected.
- Note: The CHW pump control is consistent with the example models in `Buildings.Applications.DataCenters.ChillerCooled.Examples`. This control is also consistent with the information we were able to gather on CU Boulder's district cooling system (and the model for the DC paper, which I confirmed does not have these fast oscillations). Thus, I think the overall design is acceptable, assuming the controllability issues can be resolved.

**In progress:**
For the complete district cooling system example `*DHC.Examples.Cooling.DirectUncontrolledETS`:
- At the buildings, the ETS (`*.DHC.EnergyTransferStations.Cooling.DirectUncontrolled`) was coupled with in-building distribution models that have pumps (with ideal mass flow rate inputs) (`*.DHC.Loads.BaseClasses.FlowDistribution`). 
- In addition to causing unrealistically high `dp`'s at the building-side pumps, this combination does not exist in reality. The direct uncontrolled ETS should only be used with building distribution models that do not have in-building pumping. 
- The `FlowDistribution` model was design with optional pumps, so I can easily disable them via `have_pum`. However:
**Question**
- As shown below, the direct/uncontrolled ETS configuration needs two-way control valves for each terminal zone. Because the scope of the changes increases at this point to Antoine's models, I want to ask for your advice.
![image](https://user-images.githubusercontent.com/44682485/209012801-37807125-7d05-4831-8e76-56428f44f65c.png)
Source: ASHRAE District Cooling Guide, 2013.

**Possible solutions:**
1. (Quickest) Similar to `Buildings.Experimental.DHC.Loads.BaseClasses.Validation.BaseClasses.FanCoil2PipeHeatingValve`,  I could create a new model for `FanCoil2PipeCoolingValve`. There would then be four instances of similar fan coil models in this package. 
2. (Less duplicated lines of code) I could add the control valve as an optional pathway in `FanCoil2PipeCooling` with a Boolean parameter `have_val`. I would then replicate this same design on the heating side for consistency, thus eliminating `FanCoil2PipeHeatingValve`
3. Delete the direct uncontrolled ETS as an option for district cooling and change the example to be direct controlled, which I expect is (significantly) more common anyway.

Please let me know what you think or if you have any questions. Thanks again for your help!

**Comment by mwetter** [comment]
@khinkelman : Thanks for reaching out. The addressed problems look good. Regarding your question, I think option 2. would be best, but 3. would also be fine unless @AntoineGautier has any concerns about removing this option, which I think is not a common configuration.

**Comment by AntoineGautier** [comment]
@mwetter No concern on my end to remove the uncontrolled ETS option for DC applications.
