### ISSUE TITLE
Example SmallOffice Simulation gets error

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [lbl-srg/modelica-buildings#2913]
I have just installed the Buildings Library and tried to execute  the `ThermalZones.EnergyPlus.Examples.SmallOffice.ASHRARE***` and I get the following error

`Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information.`

If I Run `ThermalZones.EnergyPlus.Examples.SmallOffice.Uncoditioned` I have no problems

How can I solve it?

 - Modelica Buildings Library: 8.1.0
 - Modelica simulation Openmodelica
 - Operating system Ubunut 18.04

**Comment by mwetter** [comment]
@LorenzoBottaccioli : This model translates with the nightly build of OpenModelica (OpenModelica 1.19.0~dev-613-gd6e04c0), see also https://libraries.openmodelica.org/branches/master/Buildings_8/Buildings_8.html
However, simulation time is still high, which we will investigate this year.

I think the index reduction error may be due to use of an older OpenModelica version. I will close the issue, please reopen if it persists with the latest nightly build of OpenModelica.
