### ISSUE TITLE
EnergyPlus Examples work in Linux, but not on Windows 10

### ISSUE THREAD

**Issue by ramanunni** [lbl-srg/modelica-buildings#3024]
I am just trying to understand the EnergyPlus integration with OpenModelica and I was trying to run the examples:  Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse

I tried AirHeating and Unconditioned

When I run it in Windows 10 and OpenModelica 1.18.1, the examples compile successfully, however, the simulation stops with the pop-up: 
"The code execution cannot proceed because "ModelicaBuildingsEnergyPlus.dll" was not found. Reinstalling the program may fix this problem." (I don't understand the root of this error as the OPENMODELICALIBRARY/MODELICAPATH variable points to where Buildings is located and the Buildings package loads without issues and other examples seem to run)
Upon closing the pop-up, OpenModelica reads: "Process crashed Simulation process failed. Exited with code 0xffffffffc0000135."

**Version**
 - Modelica Buildings Library: 8.1.1
 - Modelica simulation environment: Openmodelica 1.18.1
 - Operating system; Windows 10

**Additional context**
When I run the same examples with the same Building version and Openmodelica environment on a Manjaro Linux environment, it works like a charm, no issues whatsoever.

**Comment by mwetter** [comment]
I think this is likely either because the EnergyPlus libraries are not installed correctly, or a compiler mismatch. First please check if the file `Resources/bin/spawn-win64/bin/epfmi.dll` is around 41MB. If it is much smaller, then you likely cloned the repository(?) and did not install git-lfs. See also https://lbl-srg.github.io/soep/download.html

If you installed using the zip file from https://simulationresearch.lbl.gov/modelica/download.html you should have all binaries. Please make sure you have the same compiler as described at https://simulationresearch.lbl.gov/modelica/download.html

**Comment by ramanunni** [comment]
Thanks for the reply. I did install using the zip file from https://simulationresearch.lbl.gov/modelica/download.html and I am pretty sure, I should have all the binaries, and I thought I had followed the installation steps. I will check again and come back to you in the coming days.

**Comment by KY2292** [comment]
Hello @mwetter , I face the same issue in Windows 10 (Exited with code 0xffffffffc0000135) with OpenModelica version 1.19.2 and Buildings library: 9.0.0. The energyPlus version is 9.6.0. However I also checked that the file Resources/bin/spawn-win64/bin/epfmi.dll is around 41MB. Do you have any recommendations ?
