### ISSUE TITLE
Critical Radiation in Solar Controller

### ISSUE THREAD

**Issue by LorsHub** [lbl-srg/modelica-buildings#3074]
In `Buildings.Fluid.SolarCollectors.Controls.SolarPumpController` the critical radiation level for the solar pump to be active is compared with the direct normal radiation. Shouldn't this be the global radiation on the tilted collector surface?

**Comment by mwetter** [comment]
@PeterGrant : Can you please verify what the rationale is for using the direct normal irradiation in `SolarPumpController`, see below
![image](https://user-images.githubusercontent.com/1329080/183221330-0f17ce0a-2e00-4176-8a60-d3279157a421.png)

I think the critical solar radiation should indeed be compared to the global radiation on the tilted collector surface rather than the direct normal irradiation.
