### ISSUE TITLE
NTU and eps calculation via Fluid.HeatExchangers.BaseClasses.epsilon_ntuZ / ntu_epsilonZ

### ISSUE THREAD

**Issue by RouvenZ** [lbl-srg/modelica-buildings#3098]
Dear all,

my issue relates to the NTU/effectiveness calculation in the Fluid.HeatExchangers package. 
Within the functions deriving NTU values from epsilon or vice versa for the **counter current flow regime** it is stated that **"eps is not defined for [a heat capacity flow ratio of] Z=1"**. This is then leading to introducing a support variable "a" being a Z capped at 0.98, if I am not mistaken. This capped variable is subsequently used for NTU/effectiveness calculation. 

The following image shows the respective code lines in [ntu_epsilonZ](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo):

![grafik](https://user-images.githubusercontent.com/75694408/186441462-6a8db03e-9a53-46e9-b0ce-72fce94a1a3f.png)

The following image shows the respective code lines in [epsilon_ntuZ](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo):

![grafik](https://user-images.githubusercontent.com/75694408/186441927-5d7387c3-2f1a-4938-940a-c2451fb7d4f7.png)

However, the equations for eps and NTU can both be smoothly and continously expanded to Z=1 (e.g. using the rule of l'Hospital). These limit values are used in other fields, for example in the "VDI-Wärmeatlas" (see chapter C1).
For eps [(epsilon_ntuZ)](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo):

![grafik](https://user-images.githubusercontent.com/75694408/186447541-07fc1098-48a2-475b-9299-392b55e9f4e5.png)

And for NTU [(ntu_epsilonZ)](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo):

![grafik](https://user-images.githubusercontent.com/75694408/186449314-dff61446-07d9-497d-a796-f71a139890af.png)

Is it possible to implement the functions accordingly? I propose something along the line of 

for [ntu_epsilonZ](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo):
  if Z < 1 then
    NTU := Modelica.Math.log((1-eps)/(1-eps*Z)) / (Z-1);
  else 
    NTU := eps/(1-eps);
  end if;

for [epsilon_ntuZ](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo):
  if Z < 1 then
    eps := (1 - Modelica.Math.exp(-NTU*(1 - Z)))/(1 - Z * Modelica.Math.exp(-NTU * (1 - Z)));
  else 
    eps := NTU/(1+NTU);
  end if;

I don't assume that cutting Z at 0.98 had a large impact so far, otherwise that issue might have been filed before. But as long as there are no Modelica- or Dymola-inherent features preventing this change, especially models with similar heat capacity flows might profit from this.

Thank you all for maintaining this impressive and extremely useful library!

Cheers
Rouven

**Comment by mwetter** [comment]
@RouvenZ : Your suggested implementation looks good "on paper" but it has two problems if it were implemented in Modelica (or any other continuous time simulator):
First, the condition `if Z < 1 then` would trigger an event, and the solver would try to find the time instant when the event happens. This is computationally costly.
Second, if `Z=1-"a very small number"`, then `Z<1`, however, in the assignment `NTU := Modelica.Math.log((1-eps)/(1-eps*Z)) / (Z-1);` the expression `Z-1` may be evaluated as zero due to floating point error and a division by zero occurs.

Hence, if this limit for `Z->1` were used, we would still need to make a transition, and write the code in a way that the problematic section is not being evaluated. I was considering such an implementation originally, but due to its higher complexity and the small error for `1 >= Z > 0.97` decided to use the current implementation.

**Comment by RouvenZ** [comment]
@mwetter Thank you a lot for your reply on this! I had suspected that the reason behind it might be floating point errors. 

> First, the condition `if Z < 1 then` would trigger an event 

Does this happen only if `if Z < 1 then` appears outside the `smooth`-operator? 
If no: then there is no additional event trigger as we lose the `if Z < 0.97 then`-part instead.
If yes: I refined my code proposal accordingly below to now have the `if`-clause inside the smooth operator. 

>  then `Z<1`, however, in the assignment `NTU := Modelica.Math.log((1-eps)/(1-eps*Z)) / (Z-1);` the expression `Z-1` may be evaluated as zero

This might be solved by creating the denominator (`Z-1` in case of NTU, `1 – Z * Modelica.Math.exp(-NTU*(1-Z)) ` in case of eps) as a variable first, try the `if`-condition on this new variable and use it in critical places, what do you think? 

For [NTU](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo): 
```
a := 1 - Z;
NTU := smooth (1, if a > 0 then Modelica.Math.log((1-eps*Z)(1-eps)) / a else eps/(1-eps))
```

For [eps](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo): 
```
a := 1 – Z * Modelica.Math.exp(-NTU*(1-Z)); 
eps := smooth(1, if a > 0 then (1 – Modelica.Math.exp(-NTU*(1 - Z)))/ a else NTU/(NTU+1))
```

The total amount of declared variables does not change, as `a` is just declared differently. On the contrary, this would get rid of two function calls (`smoothMin` and `regStep`). 

Thank you for your consideration and have a nice day!

**Comment by mwetter** [comment]
The main problem of your suggested implementation is that `a` may be bigger than 0 but close to machine precision, in which case dividing an expression by something that is at the limit of the machine precision is not well defined (it may work, but would need some rigorous understanding of how different tools and languages treat this, so this is risky). This would need to be very clearly understood to make sure it works across the various Modelica implementations and computer languages to which Modelica may be translated.

To address the above paragraph, you would hence likely need a transition region, hence `smoothMin` or similar is still needed.
You will also need to ensure that the first derivative is continuous at this transition (as this is a requirement for `smooth(1, ...)`.

A minor detail is that you need to use the `noEvent` declaration in addition to `smooth`, see the Modelica Language Standard. Otherwise a tool is allowed to evaluate the `if` branch even if the condition is not satisfied.

Such an implementation change would need quite some work (formal understanding and testing of the performance and robustness), and also would require a validation cases that ensures continuity of the first derivative.
