### ISSUE TITLE
Model does not simulate as Exported FMU 

### ISSUE THREAD

**Issue by davidefop** [lbl-srg/modelica-buildings#3271]
I am trying simulate a Modelica model. It simulates fine in the OpenModelica OMEdit environment. However, **once exported as a Model Exchange FMU, it does not run with PyFMI**. 
The problem seems to be at the initialization of the model: 

```
division leads to inf or nan at time 4.44471e-12, (a=nan) / (b=1991.17), where divisor b is: component.dynBal.m
```
where _component_ is an instance of the `Buildings.Fluid.MixingVolumes.MixingVolume` class, connected to multiple fluid (water) ports (4, 2 incoming and two leaving fluxes). 

Since in OpenModelica the model simulates, I guess the problem relies either:

- in the way OpenModelica compiles the FMU;
- in the Assimulo CVODE solver;     

are there any workarounds? It must be noted that the MixingVolume must include a heat loss as a function of the internal temperature, therefore `prescribedHeatFlowRate=false` should be set. 

I should note that similar problems arise with many components of different kinds (see https://github.com/lbl-srg/modelica-buildings/issues/3169), so a general way to work around those could useful.

Thanks

**Comment by mwetter** [comment]
I am not aware of a work-around. This seems to be a problem caused by OpenModelica's FMU export or by PyFMI and I suggest you report it to one of their repositories, together with a small model that illustrates it. Also, you could try to run it with another FMU simulator to further isolate whether the problem is likely in the FMU or in PyFMI.
