### ISSUE TITLE
missing input icon

### ISSUE THREAD

**Issue by mbonvini** [lbl-srg/modelica-buildings#329]
in model

Electrical/AC/OnePhase/Storage/Battery.mo

the load model misses the input P despite its present in the equation.

**Comment by mbonvini** [comment]
This is visible when using an older version of Dymola (Version 2014 FD01 Beta 3, 2013-10-01), should we close it?

**Comment by mwetter** [comment]
This is a bug in Dymola. If in `Buildings.Electrical.AC.OnePhase.Storage.Battery`, the parameter `mode` in `bat` where assigned directly in the instantiation and not the `constrainedby` declaration, then the connector is visible.
I suggest you close it and report it to Dassault so it can be fixed in future Dymola versions.

**Comment by mbonvini** [comment]
Dymola related problem
