### ISSUE TITLE
preDro.port_a.h_outflow and port_a.h_outflow

### ISSUE THREAD

**Issue by yasir-864** [lbl-srg/modelica-buildings#3402]
**Describe the bug**
In **Buildings.Fluid.FixedResistances.Pipe**, nominal values of **preDro.port_a.h_outflow**, **port_a.h_outflow**, **preDro.port_b.h_outflow** and **port_b.h_outflow** for ports a and b are missing. 

The nominal values for preDro.h_outflow and h_outflow cannot be edited. Without these values, Dymola takes ages to calculate the model. For instance, a pipe model for 4 days took a few hours. 

**To Reproduce**
The problem doesn't appear if I connect single pipe with boundary condition and with a single heat port connection. However, this problem arises in my model that is a bit complex. If you want to see my model, I can share through some means. 

**Expected behavior**
Would you please help me how can I solve this issue for now and improve this piece of code in the upcoming versions.

**Screenshots**
Here is the screenshot. 
<img width="422" alt="error" src="https://github.com/lbl-srg/modelica-buildings/assets/134049087/4e1dbd9f-5769-450a-a525-dc69f3dc5856">

**Version**
 - Modelica Buildings Library: [8.0.1, 2021-06-08 (2021-06-08)]
 - Modelica simulation environment: Dymola
 - Operating system : Desktop Windows 10 Enterprise

**Comment by mwetter** [comment]
I don't quite understand your suggestion. `Pipe` and `Pipe.preDro` both extend from `PartialTwoPort` which sets the nominal attribute:

![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/e1244b88-92ea-4098-a0b6-5b2451006422)

Your print screen shows that your model assigns them to a non-literal value, which Dymola cannot do and hence issues the warning. (This would be good to report to Dassault so that Dassault also sees this request from different users.)

The assignment of the nominal attribute is here:
```modelica
  Modelica.Fluid.Interfaces.FluidPort_a port_a(
    redeclare final package Medium = Medium,
     m_flow(min=if allowFlowReversal then -Modelica.Constants.inf else 0),
     h_outflow(start = Medium.h_default, nominal = Medium.h_default))
    "Fluid connector a (positive design flow direction is from port_a to port_b)"
    annotation (Placement(transformation(extent={{-110,-10},{-90,10}})));
  Modelica.Fluid.Interfaces.FluidPort_b port_b(
    redeclare final package Medium = Medium,
    m_flow(max=if allowFlowReversal then +Modelica.Constants.inf else 0),
     h_outflow(start = Medium.h_default, nominal = Medium.h_default))
    "Fluid connector b (positive design flow direction is from port_a to port_b)"
    annotation (Placement(transformation(extent={{110,-10},{90,10}})));
```
These are public variables so you can override them when you declare the model instance.

**Comment by yasir-864** [comment]
Thank you so much for your time and explanation. I got it.
