### ISSUE TITLE
Update pumps and fan models in experimental DHC package

### ISSUE THREAD

**Issue by EttoreZ** [lbl-srg/modelica-buildings#3610]
This issue keeps track of the effort in cleaning the `Buildings.Experimental.DHC` package by updating the pump and fan models used in the package. 

- In particular updating the pump model  [Buildings.Experimental.DHC.EnergyTransferStations.BaseClasses](https://simulationresearch.lbl.gov/modelica/releases/v10.0.0/help/Buildings_Experimental_DHC_EnergyTransferStations_BaseClasses.html#Buildings.Experimental.DHC.EnergyTransferStations.BaseClasses.Pump_m_flow) with the preconfigured one present in Buildings [Buildings.Fluid.Movers.Preconfigured](https://simulationresearch.lbl.gov/modelica/releases/v10.0.0/help/Buildings_Fluid_Movers_Preconfigured.html#Buildings.Fluid.Movers.Preconfigured.FlowControlled_m_flow).  This update will be carried out within issue #3431 
- The fan models present in the package will be updated in the specific pull request.

**Comment by dhblum** [comment]
Much of this addressed, especially pumps, in https://github.com/lbl-srg/modelica-buildings/pull/3642.

**Comment by dhblum** [comment]
@EttoreZ after chatting with @mwetter we decided the fans in the fan coil unit models don't need to be changed to the euler method because they are mass-flow controlled and operating with constant system curves.  So there's not much that would change.  Therefore, I think this issue can be closed since the pumps were changed out in #3642.  If you agree, please close this issue.

**Comment by EttoreZ** [comment]
@dhblum I agree with what you and @mwetter concluded, so I am going to close the issue.
