### ISSUE TITLE
Excessive chattering in hysteresis-based controller

### ISSUE THREAD

**Issue by casella** [lbl-srg/modelica-buildings#3735]
The Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer model causes some chattering of the hysHea controller, which switches about every 10 seconds. The problem is that the reporting interval is 3600 s (one hour) for a simulation of 504800 s (six days), so OMC detects more than 100 events within one reporting interval and interpret it as chattering.

The default behaviour is to give a warning and go ahead, but when we test libraries we activate a flag to turn this into an error, to avoid simulations stuck in chattering to go on forever.

The question is: does it make sense to have such a frequent switching? If so, we can adapt the chattering detection logic, or maybe you could reduce the reporting interval to, say, 600 s. If not, maybe you should re-tune the controllers, see discussion in OpenModelica/OpenModelica#11006

**Comment by mwetter** [comment]
Such high frequency oscillations should not occur.
@dhblum : Can you please look into this and retune the controller?
If it can be fixed with retuning, it should also be back-ported to 9 and 10 maintenance branches.

**Comment by dhblum** [comment]
Ok will take a look, likely tomorrow.

**Comment by dhblum** [comment]
Hysteresis based on heating control signal (PI output) caused fan on/off to chatter.  Propose a fix that adjusts hysteresis for heating to be based on room temperature and setpoint error instead, and with a broader deadband.  More appropriate formulation I think, removes chatter, and reduces simulation time by 2x in the 6-day unit test.  See below (/1 original vs /4 new).

@mwetter Do release notes need to be updated in both 9 and 10 maint branches?  I suppose not master (11) since 10 are updated.  But update 10 if 9 is updated?  Not sure how this works.

<img width="1159" alt="Screen Shot 2024-03-28 at 4 24 30 PM" src="https://github.com/lbl-srg/modelica-buildings/assets/19480999/8818b6b8-eb18-4d52-a49f-8bc0f08f0b63">

**Comment by mwetter** [comment]
@dhblum : Release notes will only need to be updated for 9.1.x. I will then copy them to the 10 maintenance and the master prior to the respective releases.

**Comment by casella** [comment]
@mwetter, this kind of frequent switching should be probably avoiding, but on a second thought, I would not classify it as "chattering". See the discussion in [#12190](https://github.com/OpenModelica/OpenModelica/issues/12190#issuecomment-2042554379). Feel free to add your comment there if required.
