### ISSUE TITLE
Couldn't change medium in Buildings.Fluid.Storage.StratifiedEnhancedInternalHex

### ISSUE THREAD

**Issue by leodaniel** [lbl-srg/modelica-buildings#3743]
Hi everyone. I am using the Modelica Buildings library to model a solar water heater. I cannot change the 'Medium in the heat exchanger' in 'MediumHex' under the Heat exchanger in Buildings.Fluid.Storage.StratifiedEnhancedInternalHex. 

![Capture](https://github.com/lbl-srg/modelica-buildings/assets/22875367/544f2706-3879-4311-8d02-4fc8ea50d0ae)

In the image above, I can change the medium in 'Medium in the component' with the drop-down box, but for MediumHex, there is no drop-down box. If I right-click and edit it to Water and click OK, it gives an error "Some of the given parameters values were illegal. Redeclare of package MediumHex used unknown package". I am new to Modelica, so I don't know if this is an issue or if I do not know how to change the medium.

Thanks.

**Comment by hcasperfu** [comment]
Greetings!
This is expected behaviour.
The dropdown list is generated by the `choices` annotation.
`Medium` was declared in a general-use base class and given a list of choice (or in fact a restriction).

https://github.com/lbl-srg/modelica-buildings/blob/06c76929c08fd2c08a8ba8bc73a15d333ff670fc/Buildings/Fluid/Storage/BaseClasses/PartialTwoPortInterface.mo#L5-L14

`MediumHex` was declared in a higher-level and specialised class without this annotation, hence no dropdown list.

https://github.com/lbl-srg/modelica-buildings/blob/06c76929c08fd2c08a8ba8bc73a15d333ff670fc/Buildings/Fluid/Storage/StratifiedEnhancedInternalHex.mo#L6-L8

I cannot reproduce the error you reported when I replace `tan.MediumHex` from `Medium_2` in the text edit with `Buildings.Media.Water`.
Please note that it is not recommended to change `tan.MediumHex` directly but you should change `Medium_2` instead. `Medium_2` is used as the medium model for all components in the same loop, so that when it needs to be changed it can be all changed consistently through this propagation.

For general questions that are not bug reports/feature requests please post in https://github.com/lbl-srg/modelica-buildings/discussions. :)

Cheers,
Casper
