### ISSUE TITLE
How to use Building.Fluid.Sources.MassFlowSource_T model

### ISSUE THREAD

**Issue by danggongfan** [lbl-srg/modelica-buildings#376]
I don't know how to use this model. Even when I make a very simple test like this
![qq 20150313203641](https://cloud.githubusercontent.com/assets/10896588/6638456/29e927d6-c9c1-11e4-94fd-f2bb29c48533.png)
three errors are appeared
![qq 20150313203720](https://cloud.githubusercontent.com/assets/10896588/6638457/2a34c934-c9c1-11e4-95d4-882e6d95db97.png)
 When the parameter "use_X_in" select "false" and give a const to "X", no errors are appeared. There is no examples I can learn from the Buildings library, so I wish you can tell me how to use this model in a right way.
Thanks a lot !

**Comment by mwetter** [comment]
Based on the graphic I cannot tell whether you connected both input ports of the connector `boundary.X_in`.
Please see `Buildings.Fluid.Sensors.Examples.RelativeHumidity` for an example and let us know if this solves your problem. Otherwise, please post your model and the version of the library that you are using.

**Comment by danggongfan** [comment]
Thank you, the model can used correct. But what's the different between "MassFlowSource_T.X_in[1]" and "MassFlowSource_T.X_in[2]".

**Comment by mwetter** [comment]
The sum of these two components is one. X_in[1] is water vapor, X_in[2] are the other components of air.
