### ISSUE TITLE
When I change the azimuth of Buildings.Rooms.Examples.OnlyExteriorWallWithWindow, the temperature of room changed a little

### ISSUE THREAD

**Issue by danggongfan** [lbl-srg/modelica-buildings#379]
The default azimuth of Buildings.Rooms.Examples.OnlyExteriorWallWithWindow is W. But when I change the azimuth to E, the room's temperature almost the same, like this:
![10](https://cloud.githubusercontent.com/assets/10896588/6659445/9fffe54e-cbc0-11e4-8953-d46d56591abb.png)
When I change the azimuth of Buildings.Rooms.Examples.MixedAirFreeResponse.roo.datConExtWin from N to S, the difference become huge, like this:
![11](https://cloud.githubusercontent.com/assets/10896588/6659506/f525a634-cbc1-11e4-9ccb-583d68d0fbef.png)
Why the two examples have different situation. 
We want to build a room model only exterior wall with window, the partition wall is neglected and no floor and ceiling. Which example can I reference.

**Comment by mwetter** [comment]
@danggongfan : 

You will need a floor in your room as the model assumes that the solar radiation hits the floor, and then is reflected to other surfaces.

The results of `OnlyExteriorWallWithWindow` are correct. You do not see a noticeable change in results because the model declares that the room only has a floor and a ceiling:
```
til={Buildings.HeatTransfer.Types.Tilt.Floor, Buildings.HeatTransfer.Types.Tilt.Ceiling}
```
Therefore, changing the orientation from east to west does not affect the results.

Note that the models in the package `Buildings.Rooms.Examples.TestConditionalConstructions` are not representative of real rooms. See also the info section of this package. They are only implemented to test the correct implementation of the elements in the room model.

**Comment by danggongfan** [comment]
Thank you. Is Buildings.Rooms.Examples.MixedAirFreeResponse representative of real rooms? And I want to build a room in  the middle of building, so the heat transfer between room and outside is only through exterior wall without roof and ceiling. How do I setting the parameter of Building.Rooms.MixedAir to make the model suit my situation.

**Comment by mwetter** [comment]
You should configure your own room to make sure you have a room in a climate that is representative to answer your question. See the user guide of the `Buildings.Rooms` package for how to construct a room.

**Comment by danggongfan** [comment]
Thank you.
