### ISSUE TITLE
The parameter P_nominal should be disabled if it is not used by a model configuration

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#382]
In `Buildings.Electrical.AC.ThreePhasesBalanced.Loads.Examples.ParallelLoads`, the instance `varRL_P` uses the power from the input connector. Therefore, the parameter `P_nominal` is not used in this model configuration. It must therefore be disabled using `annotation(Dialog(enable=xxx))`.

Please verify that this is also done for other models in the `Electrical` package.

**Comment by mbonvini** [comment]
This is how is implemented in the base class `Buildings.Electrical.Interfaces.Load`
<pre>
parameter Modelica.SIunits.Power P_nominal 
    "Nominal power (negative if consumed, positive if generated)"
    annotation(Evaluate=true,Dialog(group="Nominal conditions",
        enable = mode <> Buildings.Electrical.Types.Load.VariableZ_P_input));
</pre>

The problem was caused by the value of the parameter `mode` in the load model. If this does not have the full path `Buildings.Electrical.Types.Load.VariableZ_P_input` then the parameter is not disabled.
Ater the check I haven't seen other occurrences of the problem.
Corrected in commit 657573e62a55b6490470676a4a9318875e851b3a
