### ISSUE TITLE
Simplify Templates.Components.Controls.StatusEmulator

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#3923]
This model is currently implemented as follows:
![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/e7780347-9788-4141-bdbf-ecf87c9a0526)

with parameters
![image](https://github.com/lbl-srg/modelica-buildings/assets/1329080/96db6f0a-bdcc-4845-905c-78b4200c6347)

This introduces two differential equations and a state event detection. The model could be done much simpler if it were to use a timer that starts when the boolean input switches to false, and after `yLim*riseTime` has passed, the output switches to `true`.

@AntoineGautier : What do you think about this simplification?

**Comment by AntoineGautier** [comment]
Not sure I understand exactly the refactoring with a timer. 
Assume the current configuration with the filter results in an actual delay time of about 2 s between the command `y1` and the returned status `y1_actual` (similar to the results from `Buildings.Templates.Components.Controls.Validation.StatusEmulator`):
- Time 0:05 - Boolean input `y1` switches to false: timer starts
- Time 0:07 - Delay time elapsed: `y1_actual` switches to true
- Time 0:10 - Boolean input `y1` switches to true: timer output and `y1_actual` switch to false?
 
However, the expected sequence of events is as follows (as in `Buildings.Templates.Components.Controls.Validation.StatusEmulator`):
- Time 0:05 - Boolean input `y1` switches to false: `y1_actual` remains true
- Time 0:07 - Delay time elapsed: `y1_actual` switches to false
- Time 0:10 - Boolean input `y1` switches to true: `y1_actual` remains false
- Time 0:12 - Delay time elapsed: `y1_actual` switches to true

In the branch `issue3923_statusEmulator` I proposed two alternative implementations using either the `delay` operator (`StatusEmulatorDelay`), or a state graph (`StatusEmulatorGraph`). 
Below are the validation model statistics for these variants compared to the original implementation using Dymola with the DASSL solver.
Based on these results, I believe StatusEmulatorDelay presents a viable alternative to the current implementation.

@mwetter, I would appreciate your feedback on these alternatives. If you identify any opportunities for further optimization, please feel free to commit additional changes to this branch.

<img width="625" alt="image" src="https://github.com/lbl-srg/modelica-buildings/assets/10965994/703a1dd8-0df2-4187-a3f1-e4310cfbd523">

**Comment by mwetter** [comment]
@AntoineGautier : I wasn't able to avoid the state events in `StatusEmulatorDelay`. I suggest we use `StatusEmulatorDelay`, but the assignment should better be
`y1_actual = y1Rea_actual > 0.5;`
rather than
`y1_actual = y1Rea_actual > 0;`
to be sure we are not exposed to any errors in floating point number representation.

**Comment by AntoineGautier** [comment]
With the `delay` operator, OCT fails to translate `Templates.Plants.Controls.HeatPumps.Validation.AirToWater` due to a `when` clause involved in an algebraic loop (see https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/623693073). I believe this comes from [the following part of MLS](https://specification.modelica.org/maint/3.6/operators-and-expressions.html#delay):

> In principle, a `delay` operator could break algebraic loops. For simplicity, this is not supported because the minimum delay time has to be given as additional argument to be fixed at compile time.

I am reluctant to use a `pre` operator to break the loop for the reason mentioned in https://github.com/lbl-srg/modelica-buildings/issues/3499#issue-1877017153.

@mwetter What do you think of the implementation with a state graph as in commit 5011a45? This gives more time-varying variables but eliminates the state events with Dymola. (At least on the basic validation model but I suspect that in models with closed-loop controls, the status variable will directly impact some state variables and trigger state events anyway.)

**Comment by mwetter** [comment]
The implementation in https://github.com/lbl-srg/modelica-buildings/commit/5011a45a20297ae275733ecd26aaf0fc320a9426 looks good to me.

**Comment by AntoineGautier** [comment]
@mwetter I updated the results and checksum based on the implementation with a state graph.
In [c4b77c9](https://github.com/lbl-srg/modelica-buildings/pull/3925/commits/c4b77c9748aa0c81d4f8436c8e1cffe3c7341534), I also modified the validation models to use `StatusEmulator` rather than a sampler based on your feedback from https://github.com/lbl-srg/modelica-buildings/pull/3863#discussion_r1670953106. I initially did not want to use the block `StatusEmulator` (which initially used the second order filter) so that all classes within `Buildings.Templates.Plants.Controls` be CDL-compliant. I added the CDL annotation `extensionBlock=true` in `StatusEmulator` so this requirement is still met with the changes from c4b77c9.

Maybe `StatusEmulator` could be moved under `Buildings.Controls.OBC.CDL.Utilities`. Although it is not needed for the development of controllers, it is likely needed for their validation. This would allow relying on a reference implementation rather than ad hoc implementations such as the one described in https://github.com/lbl-srg/modelica-buildings/pull/3863#discussion_r1670953106, or others using a `pre` block.

**Comment by mwetter** [comment]
As `StatusEmulator` is used just for emulation during simulation, and `CDL.Utilities` would need to be supported by all CDL compliant building automation systems, I doubt the 231 committee would approve inclusion of this block in the standard. I still wonder if the same functionality can be obtained with just using timers and other CDL blocks and constructs (other than an extension block). Either case if the block is used across implementations, we we could put it under `OBC.Utilities`.

**Comment by mwetter** [comment]
This can be closed as it is updated through https://github.com/lbl-srg/modelica-buildings/pull/3925
