### ISSUE TITLE
Can not use 'Buildings.HeatTransfer.Data.OpaqueConstructions.Generic'

### ISSUE THREAD

**Issue by n-marci** [lbl-srg/modelica-buildings#3944]
**Describe the bug**
When trying to describe a composite material with `Buildings.HeatTransfer.Data.OpaqueConstructions.Generic` there are translation errors.

**To Reproduce**
1. Open Example `Buildings.HeatTransfer.Examples.ConductorInitialization`
2. Copy Insulation, Brick, compositeWall and conS1 to another model
3. See error

```
[26] 10:56:05 Translation Error
[greenshell: 542:87-542:176]: [Modified element layers not found in class facade.](omeditmessagesbrowser:///greenshell?lineNumber=542)

[27] 10:56:05 Translation Error
[greenshell: 601:77-601:107]: [Component material of variability parameter has binding '({insulation, brick})[<compositeWall, compositeWall>]' of higher variability continuous.](omeditmessagesbrowser:///greenshell?lineNumber=601)

[28] 10:56:05 Translation Error
[greenshell: 603:65-603:87]: [Component layers of variability parameter has binding '(compositeWall)[<conS1, conS1>]' of higher variability continuous.](omeditmessagesbrowser:///greenshell?lineNumber=603)
```

**Expected behavior**
One should be able to reproduce the example.

**Version**
 - Modelica Buildings Library: 11.0.0
 - Connected to OpenModelica 1.23.1
 - Connected to OMSimulator 2.1.2-linux-notlm-debug
 - Ubuntu 24.04

**Comment by mwetter** [comment]
This issue is caused by OMEdit, there is nothing I see that we could change in the Buildings library. Can you please report it to the OpenModelica github site.

I tried to reproduce your reported error by copying the four instances into `Buildings.HeatTransfer.Examples.ConductorMultiLayer`. The problem is that the copy-paste operation does not copy the `parameter` attribute that is required for the data records. Once I add this on the textual level, and connect the heat ports, the model with the copied components simulates.
