### ISSUE TITLE
One phase resistive load model under electrical package (OpenModelica)

### ISSUE THREAD

**Issue by s-and** [lbl-srg/modelica-buildings#415]
Hi,
First of all, thank you very much for providing this library. I have been exploring the electrical package of this library and would like to especially thank Marco for his help so far.

There are several examples not working under OpenModelica (https://test.openmodelica.org/libraries/Buildings/BuildModelRecursive.html). I suspect that several of them involve the one phase resistive load model. For instance, to get the storage model working, I replaced the resistive load with a capacitive one and it worked.

I wonder what makes one phase resistive load model incompatible with OpenModelica as the rest of the one phase load models seem to work.

Thanks.

**Comment by mbonvini** [comment]
Regarding some of the errors flagged by OpenModelica there is a ticket open that once fixed should address the problems related with index reduction (https://trac.openmodelica.org/OpenModelica/ticket/3305). The ticket has high priority so hopefully it will be fixed soon. However, if in the meantime this error appears a quick solution is setting this option in OM

```
--replaceHomotopy=actual
```

Regarding the difference between resistive and capacitive there isn't really a conceptual difference since the `CapacitiveLoad` model extends the same model used by the `ResistiveLoad` model, and actually it the capacitive one adds a layer of complexity. However this may lead to a possible workaround that makes the model work with OM.

I'll let you know if my idea works.

**Comment by mbonvini** [comment]
@s-and - Thanks for this hint, I think I have a solution to the problem and soon should be in the master branch.

**Comment by s-and** [comment]
Thanks for taking care of this.

**Comment by mbonvini** [comment]
closed with https://github.com/lbl-srg/modelica-buildings/pull/416
