### ISSUE TITLE
Review of Buildings.Fluid.Chillers.Carnot

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/modelica-buildings#471]
This issue contains the review of the `Buildings.Fluid.Chillers.Carnot` model which will potentially be merged in `Annex60` (see https://github.com/iea-annex60/modelica-annex60/issues/353)

**Comment by damienpicard** [comment]
`Buildings.Fluid.Chillers.Carnot` uses its own equation to calculate `staA2` and `staB2`. The equations are however very similar to the ones contained in its partial class `Buildings.Fluid.Interfaces.PartialFourPortInterface`.

The differences are: `Carnot` allows homotopy initialization while `PartialFourPortInterface` does not and `PartialFourPortInterface` uses `noEvent`:

`Carnot':
```
staA1=Medium1.setState_phX(port_a1.p,
                          homotopy(actual=actualStream(port_a1.h_outflow),
                                   simplified=inStream(port_a1.h_outflow)),
                          homotopy(actual=actualStream(port_a1.Xi_outflow),
                                   simplified=inStream(port_a1.Xi_outflow)));
```

`PartialFourPortInterface`
```
  Medium1.ThermodynamicState sta_a1=
      Medium1.setState_phX(port_a1.p,
                           noEvent(actualStream(port_a1.h_outflow)),
                           noEvent(actualStream(port_a1.Xi_outflow))) if 
         show_T "Medium properties in port_a1";
```

Why not merge these equations?

**Comment by damienpicard** [comment]
The efficiency calculation is done using either the inlet, the volume temperature or the average between the two. The user can chose using i.e. the parameter `effInpCon`. However, I find the following configuration a bit confusing:
Imagine that the user chooses `effInpCon == Buildings.Fluid.Types.EfficiencyInput.port_a` and allows `flowReversal`. Then the used `TCon = vol1.heatPort.T` (instead of `port_b.T`). That means that the efficiency of the Carnot model depends on the flow direction, which is probably not wished.

The following equations could be adapted to solve that issue:
```
  if effInpCon == Buildings.Fluid.Types.EfficiencyInput.volume then
    TCon = vol1.heatPort.T;
  elseif effInpCon == Buildings.Fluid.Types.EfficiencyInput.port_a then
    TCon = Medium1.temperature(staA1);
  elseif effInpCon == Buildings.Fluid.Types.EfficiencyInput.port_b then
    TCon = Medium1.temperature(staB1);
  else
    TCon = 0.5 * (Medium1.temperature(staA1)+Medium1.temperature(staB1));
  end if;
```

**Comment by damienpicard** [comment]
The current implementation is only for cooling. It would be useful to extend the current model to heating.

**Comment by mwetter** [comment]
@damienpicard Thanks for the review. Here are some comments:
- I agree that a Carnot heatpump would be good. We just developed first implementations (that need revisions before being put on the `Buildings` master and the `Annex60` repository). We have a Carnot heatpump with leaving outlet temperature as control signal (https://github.com/lbl-srg/modelica-buildings/blob/issue467_districtHeatingCooling/Buildings/Fluid/HeatPumps/Carnot_TCon.mo) and similar for a Carnot chiller (https://github.com/lbl-srg/modelica-buildings/blob/issue467_districtHeatingCooling/Buildings/Fluid/Chillers/Carnot_TEva.mo)
- The variable `staA1` (and similar) must stay in the Carnot model because the ones in `PartialFourPortInterface` are for efficiency reason conditionally removed if `show_T=false`. Hence, it is illegal to use them in an equation section. They can only be used for reporting.
- Regarding reverse flow, looking at the implementation of computing `staA1`, I think it would be better to compute `staA1` always assuming flow in the design direction. If there is reverse flow, then this is usually due to numerical reasons if the pump is off as I don't see why a user would run a chiller with reverse flow while it is switched on. Under this scenario, we can avoid the use of `actualStream` and probably get in some systems simpler equations.

Hence, I see the need for the following:

- [ ] Add a Carnot heat pump, and rename these models to `Carnot_y` (similarly than for the heater/cooler) to avoid a clash in names.
- [ ] Medium term, also move `HeatPumps/Carnot_TCon.mo` and `Chillers/Carnot_TEva.mo` to `Annex60`.
- [ ] Consider removing `actualStream` in computing the states that are used to compute the Carnot efficiency.

**Comment by mwetter** [comment]
Closed as this is now on the master of the Buildings library and also dealt with in https://github.com/iea-annex60/modelica-annex60/pull/400
