### ISSUE TITLE
[JModelica.org] C89 compliant header files

### ISSUE THREAD

**Issue by jonathankampemodelon** [lbl-srg/modelica-buildings#569]
JModelica.org needs C89 compliant header files for external functions. Buildings/Resources/Include/bcvtb.h contains // comments. Could you please replace these with /* */ ?

**Comment by mwetter** [comment]
@tianwei1989 
Can you please also correct the files used by the CFD program in `Buildings/Resources/C-Sources`

Below is a (partial) output of the type of problems that occur when compiling these files from JModelica which requires C89 compliant files:
[compilation_output.txt](https://github.com/lbl-srg/modelica-buildings/files/598872/out.txt)
I am not sure if these syntax errors cause the compilation to fail.

**Comment by tianwei1989** [comment]
@mwetter Sure. I will look at those errors. Wei

**Comment by tianwei1989** [comment]
@mwetter @zuowangda  Dr. Wetter, I looked at the error message. I agree that the error message is sent due to the syntax error. It is corrected in branch `issue569_bcvtb`. I just cleared up the syntax error in FFD source codes. I am going to send a pull request, with which the error should be eliminated.
