### ISSUE TITLE
Buildings.Fluid.Movers not compatible with Modelica.Media.Air.MoistAir

### ISSUE THREAD

**Issue by yfuerst** [lbl-srg/modelica-buildings#737]
I modelled a small example consisting of two `Boundary_pT` and one `FlowControlled_m_flow` with arbitrary parameters. For the media model I chose `Modelica.Media.Air.MoistAir`. The translation ist aborted with the error

Cannot find differentiation function:
Modelica.Media.Air.MoistAir.T_phX(bou.p, fan.port_a.h_outflow, {0.01, 0.99})
with respect to time

Failed to differentiate the equation
fan.vol.dynBal.m = fan.vol.dynBal.fluidVolume*smooth(2, bou.p/( gasConstant_Unique15(
setState_phX_Unique10(bou.p, fan.port_a.h_outflow, {0.01, 0.99}))*smooth(2, Modelica.Media.Air.MoistAir.T_phX(bou.p, fan.port_a.h_outflow, {0.01, 0.99}))));

in order to reduce the DAE index.

Failed to reduce the DAE index.

Does anyone have a suggestion for me on where I should perform some model adjustments? Is the error more likely to be solved in the media or the mover model?

**Comment by mwetter** [comment]
If the control volume in your fan has a dynamic mass balance, then you have a high index DAE. Try configure it as a steady-state model.

**Comment by yfuerst** [comment]
That works, thank you very much. Is there any way to get the model working with a dynamic mass balance? Do you have any literature suggestions, so can I fully understand the problem?

**Comment by mwetter** [comment]
I would need to see your model to understand why exactly it fails, but most likely you connected the fan with a dynamic mass balance (which gives an expression for dm/dt = ... dp/dt ) to a boundary model that sets p = constant. You can also try to use Buildings.Media.Air, or better, add a resistance because a dynamic mass balance connected directly to a fixed pressure is probably not the physics you want to simulate.

See also https://github.com/lbl-srg/modelica-buildings/wiki/Style-Guide for how to diagnose if Dymola fails to differentiate a function.

You may want to look at http://epubs.siam.org/doi/abs/10.1137/0914043 regarding index reduction.

**Comment by yfuerst** [comment]
Thank you very much for all the additional information.
