### ISSUE TITLE
OffTimer initial conditions

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#756]
```Buildings.Controls.Continuous.OffTimer``` measures time from the latest ```off``` signal (the moment when a ```boolean``` input became false). The issue is that if in time 0 the input signal is ```true```, the timer still gets kicked on, although it should not, and measures time until the first ```off``` signal. After the first ```off``` instant the model performs as expected.

**Comment by mwetter** [comment]
@milicag I think the current behavior is as expected. The info section says

> Block that records the time that has elapsed since its input signal switched to false. 
At the beginning of the simulation, this block outputs the time that has elapsed since the start of the simulation. Afterwards, whenever its input switches to false, the timer is reset. 

This gives a sawtooth output signal, and the output is strictly increasing until it gets reset. If we were to not start the time, its output would be flat once, and afterwards a saw tooth. I think this would be harder for downstream components to interpret or process.

Maybe you could use `Modelica.Blocks.Logical.Timer` in your application.

**Comment by milicag** [comment]
Yeah, the timer in a correct component for my application. My concern is that current behavior of the ```OffTimer``` block violates the quote below by initiating the timer regardless of the status of the initial signal, and behaves as expected as the input signal turns off for the first time. 
> Block that records the time that has elapsed since its input signal switched to false.

It just depends on the application of the block, so I felt it should get brought up. This block, as is, is a timer started at time 0 and gets reset each time input signal switched to false. Maybe a note in the documentation would help.

**Comment by mwetter** [comment]
@milicag I will close this and correct it in https://github.com/ibpsa/modelica-ibpsa/issues/780 as this model is from the IBPSA library.
