### ISSUE TITLE
Integers Equal block

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#788]
Add an ```Equal``` block to ```Integers```. It should have integer type inputs.

Evaluate ```Logical.Equal``` - check if there is an equal block with real inputs in ALC, etc. Possibly remove this block based on that.

**Comment by milicag** [comment]
@JayHuLBL I'm assigning this to you, since you've been working on the equal blocks, but feel free to bounce it back for any reason.

**Comment by mwetter** [comment]
@JayHuLBL : The reason for removing it is because testing real numbers for equality is only defined if a tolerance is specified (your implementation uses a tolerance) as otherwise rounding errors can affect the result. If control systems don't include such a block, it would be better to remove it from CDL. If they include a block and we keep it because we use it, then the tolerance needs to be exposed as a parameter.

**Comment by JayHuLBL** [comment]
@mwetter There is one micro block `True if=variable`  in ALC EikonLogic, to generate True/False output when its both inputs are same/different. I think we could keep the block in CDL but expose the tolerance as a parameter.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please remind me whether ALC has a data type Integer? Also, does ALC state what equality means if the inputs are Real signals? For example, does something like 1.0000000001 = 1 yield true or false?  Or if there is no integer data type in ALC, would 0.51 = 1.49 be true or false? It seems that we need to be very careful with such an implementation and with how it is being used by users and then converted to product lines, which is fine if we are explicit about the tolerance. But in case ALC does not say what equality means, I would rather write sequences that do not use this block. Also, if ALC (and other vendors) states what equality means, then all vendors should expose the tolerance as a parameter as otherwise different implementations can give different results which makes verification non-deterministic.

**Comment by milicag** [comment]
@JayHuLBL

**Comment by JayHuLBL** [comment]
@mwetter ALC EikonLogic does not have the specific Integer data type. It uses the resolution  format to control (truncate) the block output values on the number of digits after decimal, e.g.  0.01 means two digits to the right of decimal, 0.1 means one digits to the right of decimal and 1 means whole number. However, ALC does not say what equality means.

**Comment by milicag** [comment]
@mwetter @JayHuLBL I'm implementing enumerations converted to integers as comparative values for the integer inputs (which works fine now that I've figured it out) and I'd like to use an equal block that contains integer inputs, and would even like to have an equal block with a parameter replacing the second input (something similar to e.g. ```GreaterEqualThreshold```).

Is there a chance we'll be implementing those, or should I stick to ```IntToRea``` conversions and equality blocks with Real inputs?

**Comment by mwetter** [comment]
@milicag As we don't often use integer comparison with `GreaterEqual` I suggest we convert to real and then test for inequality.

**Comment by milicag** [comment]
@mwetter Yeah, we'd need all of the ```=, <, >, etc.``` blocks in that case for the sake of consistency. I'll simply keep using conversions.
