### ISSUE TITLE
Cooling and heating loop signals (uHea and uCool)

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#839]
Implement a PI control loop that generates cooling (```uCool```) and heating (```uHea```) loop signals such to maintain ```TZon``` at ```TCooSet``` and ```THeaSet```, respectively.  Create both a single zone and a multiple zone version of the loop.

**Comment by milicag** [comment]
I created this block on ```issue841_closed_loop_single_zone```. The block is fully functional, although currently it needs images and one more run through the info section.

**Comment by milicag** [comment]
I migrated this to a separate branch, ```issue839_uhea_ucoo_loop```.

**Comment by JayHuLBL** [comment]
@milicag The input to block `greThrHea` is from LimPID controller `conHeaVal` with lower output limit of `conSigMin`. The same value is used as threshold in `greThrHea` block.
In Dymola simulation, the `conHeaVal` output will not achieve exactly its minimum output `conSigMin` but has numerical difference (in the order of 10^(-15) ~ 10^(-60)?). 
In order to see "returning false as soon as the input signal becomes zero", you can either set the lower output limit of `conHeaVal` to be `conSigMin - CDL.Constants.eps`, or  set the threshold value of `greThrHea` to be `conSigMin + CDL.Constants.eps`.

**Comment by milicag** [comment]
@JayHuLBL Thanks! There seems to be a time period after which the signal does obtain value 0. Is that how things are set up?

**Comment by JayHuLBL** [comment]
@milicag In package `Modelica.Constants`, there is a constant `eps = ModelicaServices.Machine.eps`. The `eps` value defines `Biggest number such that 1.0 + eps = 1.0`. I  don't know if it is a time period that the signal becomes 0, or it is because the value becomes lower than `0 + eps`. The `eps` value depends on machine (`[https://stackoverflow.com/questions/19141432/python-numpy-machine-epsilon]`).

**Comment by mwetter** [comment]
@milicag : The problem is caused by the various inequality tests. You need to use hysteresis instead of inequality checks. See Section 2.7 in http://simulationresearch.lbl.gov/modelica/userGuide/bestPractice.html#controls
