### ISSUE TITLE
development branch for VAV case study

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#967]
This branch is used to modify `VAVReheat` for the case study.

**Comment by mwetter** [comment]
The following needs to be verified
- [ ] conAHU.outAirSetPoi.sysVenEff.y is negative, but efficiencies should never be negative. This can be reproduced running 
```
simulateModel("Buildings.Examples.VAVReheat.Guideline36", startTime=12960000, stopTime=13046400, method="Radau", tolerance=1e-06, resultFile="Guideline36");
```

**Comment by JayHuLBL** [comment]
@mwetter Cause and solution of the "conAHU.outAirSetPoi.sysVenEff.y is negativ" issue:
When it switches to occupied mode, the required zone discharged airflow rate is increased from 0 (min airflow rate when in cool-down mode) to occupied min airflow rate (which could be equal to min zone airflow rate that is set in model `conVAVCor.actAirSet`). 
Currently, the zone minimum airflow set point `VMin` is equal to 0.1*V_flow_nominal, which is too low. As the value would be lower than the required minimum outdoor airflow rate to the zone (Voz).
When running simulation, the zone minimum airflow set point `VMin` would become the discharge airflow set point to the zone. Also the `damPosCon` PI controller will try to increase the damper position so to give higher discharge airflow rate (which always takes some time to achieve the setpoint).

So both issues [VMin<Voz, VDis<(VDisSet=VMin)] causes the problem in block `conAHU.outAirSetPoi.priOutAirFra`. 
Inputs of the block are u1=Voz, u2=VDis. If everything is correct, the primary airflow rate (which is also called discharge airflow rate) VDis should definitely be larger than Voz. But here, since Voz>VDis, the output becomes much more than 1, so that `conAHU.outAirSetPoi.sysVenEff.y` becomes negative.

Solutions:
- [ ] change the VMin to be a higher value so to be more required outdoor airflow.
- [ ] and also in the OutsideAirflow block, create logical to by-pass the situation when the real VDis is less than Voz.

**Comment by JayHuLBL** [comment]
- [ ] zone temperature oscillation observed when it achieves the cooling set point. It seems that the VDisSet changes frequently.
